<a href="https://colab.research.google.com/github/engrsakib/AI-ML-Learning/blob/AI-ML/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

arr = np.array([1, 2, 3])

arr2 = np.array([[1, 2], [1, 1]])

print(arr2.ndim)

print(arr * 5, type(arr))

2
[ 5 10 15] <class 'numpy.ndarray'>


In [16]:
rn = np.random.uniform(1, 10, (3, 3, 4))
print(rn)

[[[6.0121695  4.82650327 7.85962392 6.45748674]
  [7.86609327 9.04324924 7.52747309 7.06346802]
  [6.58370216 7.34203293 3.09572375 3.26861501]]

 [[1.41504968 2.49501807 7.42424479 1.1409047 ]
  [5.31433856 3.05650114 4.22742469 8.52485468]
  [8.80233671 7.79081539 2.21621907 1.59850498]]

 [[1.17653249 2.70678978 6.20045937 6.85633513]
  [5.43182434 8.07781703 2.45197708 3.3968815 ]
  [2.38293367 4.71583113 7.86349631 5.95736405]]]


In [18]:
# np.arrange

print(np.arange(1, 10, 1).reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
